---
title: "Client Report - What's in a name?"
subtitle: "Course DS 250"
author: "David Pineda"
format:
  html:
    self-contained: true
    page-layout: full
    title-block-banner: true
    toc: true
    toc-depth: 3
    toc-location: body
    number-sections: false
    html-math-method: katex
    code-fold: true
    code-summary: "Show the code"
    code-overflow: wrap
    code-copy: hover
    code-tools:
        source: false
        toggle: true
        caption: See code

---

```{python}
#| label: libraries
#| include: false
import pandas as pd
import altair as alt
import numpy as np

from IPython.display import Markdown
from IPython.display import display
from tabulate import tabulate
```


## Elevator pitch

From this assignment, I was able to visual see from raw data the insights of specific dates of usage. I used altair to visual the data I was passing in.

```{python}
#| label: project data
#| code-summary: Read and format project data
# Include and execute your code here
dat = pd.read_csv("https://raw.githubusercontent.com/byuidatascience/data4names/master/data-raw/names_year/names_year.csv")
```

__Highlight the grand questions__

## GRAND QUESTION 1

How does David in 2002 compare to its use historically?

A analysis of the name "David" in 2002 compared to its historical use shows that the name was still popular in 2002, with a total of 17,076 uses that year. However, it is worth noting that the peak popularity of the name "David" was in 1955, when it was used even more frequently. In 2002, the name was used 1603.5 times in California, where I was born. Overall, the name "David" has remained a consistently popular choice throughout the decades, although its usage has likely decreased since its peak in the 1950s.

```{python}
#| label: GQ1
#| code-summary: Read and format data
# Include and execute your code here
# Find total usage of name in 2002
import altair as alt
import pandas as pd

# Specify the URL of the CSV file
url = "https://raw.githubusercontent.com/byuidatascience/data4names/master/data-raw/names_year/names_year.csv"

# Load the CSV file into a pandas DataFrame
data = pd.read_csv(url)

# Print total usage of name in 2002
data.sort_values("Total").query("name == 'David'").query("year == 2002")


```



```{python}
#| label: GQ1 chart
#| code-summary: plot example
#| fig-cap: "My useless chart"
#| fig-align: center
# Include and execute your code here
import altair as alt
import pandas as pd

# Specify the URL of the CSV file
url = "https://raw.githubusercontent.com/byuidatascience/data4names/master/data-raw/names_year/names_year.csv"

# Load the CSV file into a pandas DataFrame
data = pd.read_csv(url)

# Print the total
matching_rows = (data
    .query("name == 'David'")
    .sort_values("Total")
    )

# Create an Altair chart showing the usage of the name over time
alt.Chart(matching_rows).mark_line().encode(
    x=alt.X('year',axis=alt.Axis(format=".0f")),
    y='Total'
)

```




## GRAND QUESTION 2

If you talked to someone named Brittany on the phone, what is your guess of his or her age? What ages would you not guess?

Based on the chart, the peak of the name Brittany is in 1991. The most amount of the name I see, based on the chart, is from the years 1980 - 2005. From my anaylsis, their age can be from 18 - 43. I would not guess the age 50 over less than 18.

```{python}
#| label: GQ2
#| code-summary: Read and format data
# Include and execute your code here
import altair as alt
import pandas as pd

# Specify the URL of the CSV file
url = "https://raw.githubusercontent.com/byuidatascience/data4names/master/data-raw/names_year/names_year.csv"

# Load the CSV file into a pandas DataFrame
data = pd.read_csv(url)


# Print the total
matching_rows = (data
    .query("name == 'Brittany'")
    .sort_values("Total")
    )

# Create an Altair chart showing the usage of the name over time
alt.Chart(matching_rows).mark_line().encode(
    x=alt.X('year',axis=alt.Axis(format=".0f")),
    y='Total'
)

```




## GRAND QUESTION 3

Mary, Martha, Peter, and Paul are all Christian names. From 1920 - 2000, compare the name usage of each of the four names. What trends do you notice?

_type your results and analysis here_

```{python}
#| label: GQ3
#| code-summary: Read and format data
# Include and execute your code here
import altair as alt
import pandas as pd

# Specify the URL of the CSV file
url = "https://raw.githubusercontent.com/byuidatascience/data4names/master/data-raw/names_year/names_year.csv"

# Load the CSV file into a pandas DataFrame
data = pd.read_csv(url)


# Print the total
matching_rows = (data
    .query("name in ['Martha', 'Mary', 'Peter', 'Paul']")
    .query("year >= 1920 and year <= 2000")
    .sort_values("Total")
    )





# Create an Altair chart showing the usage of the name over time
alt.Chart(matching_rows).mark_line().encode(
    x=alt.X('year',axis=alt.Axis(format=".0f")),
    y='Total',
    color = 'name'
)

```







## GRAND QUESTION 4

Think of a unique name from a famous movie. Plot the usage of that name and see how changes line up with the movie release. Does it look like the movie had an effect on usage?

The movie I am chosing is The Godfather and the name from the movie is Vito. The Godfather was released in 1972 and from the chart we can see the decrease of the name after the year 1972.

```{python}
#| label: GQ4
#| code-summary: Read and format data
# Include and execute your code here
import altair as alt
import pandas as pd

# Specify the URL of the CSV file
url = "https://raw.githubusercontent.com/byuidatascience/data4names/master/data-raw/names_year/names_year.csv"

# Load the CSV file into a pandas DataFrame
data = pd.read_csv(url)


# Print the total
matching_rows = (data
    .query("name == 'Vito'")
    .query("year >= 1972 and year <= 2015")
    .sort_values("Total")
    )

# Create an Altair chart showing the usage of the name over time
alt.Chart(matching_rows).mark_line().encode(
    x=alt.X('year', axis=alt.Axis(format=".0f"))
    y='Total'
)

```





## APPENDIX A (Additional Python Code)

```python
#Hi David, Solid report on the technical side. A few things to address to get a 5: 1) Remove the commas from the years in the graphs 2) Add a marker to the graph to indicate the reference years (like a point or a dot on your birth year) 3) Show the popularity of the name Vito across the whole dataset and mark 1972 release date

```
